// Generated by https://quicktype.io
// To parse this JSON data, do
//
//     final cardStatus = cardStatusFromJson(jsonString);

import 'dart:convert';

CardStatus cardStatusFromJson(String str) {
  final jsonData = json.decode(str);
  return CardStatus.fromJson(jsonData);
}

String cardStatusToJson(CardStatus data) {
  final dyn = data.toJson();
  return json.encode(dyn);
}

class CardStatus {
  final double? imageHeight;
  final double? cardOneTop;
  final double? cardTwoTop;
  final double? cardThreeTop;

  CardStatus({
    this.imageHeight,
    this.cardOneTop,
    this.cardTwoTop,
    this.cardThreeTop,
  });

  factory CardStatus.fromJson(Map<String, dynamic> json) => CardStatus(
        imageHeight: json["imageHeight"].toDouble(),
        cardOneTop: json["cardOneTop"].toDouble(),
        cardTwoTop: json["cardTwoTop"].toDouble(),
        cardThreeTop: json["cardThreeTop"].toDouble(),
      );

  CardStatus copyWith({imageHeight, cardOneTop, cardTwoTop, cardThreeTop}) {
    return CardStatus(
        imageHeight: imageHeight ?? this.imageHeight,
        cardOneTop: cardOneTop ?? this.cardOneTop,
        cardTwoTop: cardTwoTop ?? this.cardTwoTop,
        cardThreeTop: cardThreeTop ?? this.cardThreeTop);
  }

  Map<String, dynamic> toJson() => {
        "imageHeight": imageHeight,
        "cardOneTop": cardOneTop,
        "cardTwoTop": cardTwoTop,
        "cardThreeTop": cardThreeTop,
      };
}
