// Generated by https://quicktype.io
// To parse this JSON data, do
//
//     final challenge = challengeFromJson(jsonString);

import 'dart:convert';

Challenge challengeFromJson(String str) {
  final jsonData = json.decode(str);
  return Challenge.fromJson(jsonData);
}

String challengeToJson(Challenge data) {
  final dyn = data.toJson();
  return json.encode(dyn);
}

class Challenge {
  String imageUrl;
  String title;
  String startDate;
  String cost;
  String category;

  Challenge({
    required this.imageUrl,
    required this.title,
    required this.startDate,
    required this.cost,
    required this.category,
  });

  factory Challenge.fromJson(Map<String, dynamic> json) => Challenge(
        imageUrl: json["imageUrl"],
        title: json["title"],
        startDate: json["startDate"],
        cost: json["cost"],
        category: json["category"],
      );

  Map<String, dynamic> toJson() => {
        "imageUrl": imageUrl,
        "title": title,
        "startDate": startDate,
        "cost": cost,
        "category": category,
      };
}
